CREATE TABLE IF NOT EXISTS users(
   id INT(10) AUTO_INCREMENT PRIMARY KEY,
   first_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(75) NOT NULL,
   email VARCHAR(120) NOT NULL UNIQUE,
   password TEXT NOT NULL,
   birthday DATE NOT NULL,
   created_at TIMESTAMP  NULL DEFAULT CURRENT_TIMESTAMP


);